### ISSUE TITLE
Lost Contact! 

### ISSUE THREAD

**Issue by YenHub** [developer-sid/scraper#1]
Hi Sid, 

It's Ian here, sadly, we have somehow lost your latest contact details to be able to contact you...! 

Could you kindly email one of us at SQN so we can remain in contact? 

Thanks Sid, 

Ian

**Comment by developer-sid** [comment]
> Hi Sid,
> 
> It's Ian here, sadly, we have somehow lost your latest contact details to be able to contact you...!
> 
> Could you kindly email one of us at SQN so we can remain in contact?
> 
> Thanks Sid,
> 
> Ian

Hi Ian,

Below is my contact details
email: developer-sid@outlook.com
skype: creativemirage

Thanks
Sid
